spring.application.name=MakeMyTrip
server.port=8080
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=MakeMyTrip
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.config.import=optional:file:.env[.properties]
server.compression.enabled=true
server.compression.mime-types=application/json
server.compression.min-response-size=1024
spring.data.mongodb.auto-index-creation=true
