spring.application.name=MakeMyTrip
server.port=8080
spring.data.mongodb.uri=mongodb+srv://pawansinghb07_db_user:NZ79L1qnD05Omh5C@main.wzrasyf.mongodb.net/?appName=main
spring.data.mongodb.database=MakeMyTrip
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
